# Generated by Django 5.1.1 on 2024-09-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('account', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ext_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed')], default='created', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OperationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_detail', models.TextField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.operation')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.operationtype'),
        ),
    ]
